### ISSUE TITLE
Request: implement state of ngrok into HA

### ISSUE THREAD

**Issue by Claws81** [ThePicklenat0r/hassio-ngrok#15]
Hi.
Would you consider adding the ngrok state into HA, so the current generated URL can be sent via e.g. Telegram?
I previously used this plugin, but switched to yours, due to some problems with Vincenzosuracis.:
https://github.com/vincenzosuraci/hassio_ngrok

I have absolutely no clue on how to do this myself :)
Thank to making this plugin.

Regards

**Comment by ThePicklenat0r** [comment]
Hey @Claws81, you should already be able to do this. Since all this addon does is run the ngrok client we can leverage the built in API in that to accomplish this task. Try adding this to your configuration.yaml:

```
sensor:
  - platform: rest
    resource: http://localhost:4040/api/tunnels/hass
    name: Home Assistant URL
    value_template: '{{ value_json.public_url }}'
```

I just tested this and I got a sensor added into Home Assistant with the public URL from ngrok. If you changed from the default config, you might need to update the `resource` url, just replace `hass` in the example above with whatever your tunnel name is. You can also create multiple of these so you can monitor more than one tunnel.  That will give you a similar result and then you can use an automation from there to send a notification out.

Just for reference, here's the docs for the ngrok client api: https://ngrok.com/docs#client-api
and here's Home Assistant's docs for a RESTful API sensor: https://www.home-assistant.io/integrations/rest/
